export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';


// User ActionTypes
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_ERROR = 'USER_LIST_ERROR';

export const USER_ADD_RESET = 'USER_ADD_RESET';
export const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_ERROR = 'USER_ADD_ERROR';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';


// Customer ActionTypes

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_ERROR = 'CUSTOMER_LIST_ERROR';

export const CUSTOMER_ADD_RESET = 'CUSTOMER_ADD_RESET';
export const CUSTOMER_ADD_REQUEST = 'CUSTOMER_ADD_REQUEST';
export const CUSTOMER_ADD_SUCCESS = 'CUSTOMER_ADD_SUCCESS';
export const CUSTOMER_ADD_ERROR = 'CUSTOMER_ADD_ERROR';

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_ERROR = 'CUSTOMER_DELETE_ERROR';

export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_ERROR = 'CUSTOMER_UPDATE_ERROR';


// Redeem code ActionTypes


export const REDEEM_LIST_REQUEST = 'REDEEM_LIST_REQUEST';
export const REDEEM_LIST_SUCCESS = 'REDEEM_LIST_SUCCESS';
export const REDEEM_LIST_ERROR = 'REDEEM_LIST_ERROR';

export const REDEEM_ADD_RESET = 'REDEEM_ADD_RESET';
export const REDEEM_ADD_REQUEST = 'REDEEM_ADD_REQUEST';
export const REDEEM_ADD_SUCCESS = 'REDEEM_ADD_SUCCESS';
export const REDEEM_ADD_ERROR = 'REDEEM_ADD_ERROR';

export const REDEEM_DELETE_REQUEST = 'REDEEM_DELETE_REQUEST';
export const REDEEM_DELETE_SUCCESS = 'REDEEM_DELETE_SUCCESS';
export const REDEEM_DELETE_ERROR = 'REDEEM_DELETE_ERROR';

export const REDEEM_UPDATE_REQUEST = 'REDEEM_UPDATE_REQUEST';
export const REDEEM_UPDATE_SUCCESS = 'REDEEM_UPDATE_SUCCESS';
export const REDEEM_UPDATE_ERROR = 'REDEEM_UPDATE_ERROR';


// search ActionTypes

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';

export const SEARCH_CUSTOMER_REQUEST = 'SEARCH_CUSTOMER_REQUEST';
export const SEARCH_CUSTOMER_SUCCESS = 'SEARCH_CUSTOMER_SUCCESS';
export const SEARCH_CUSTOMER_ERROR = 'SEARCH_CUSTOMER_ERROR';

export const SEARCH_HEADER_CUSTOMER_REQUEST = 'SEARCH_HEADER_CUSTOMER_REQUEST';
export const SEARCH_HEADER_CUSTOMER_SUCCESS = 'SEARCH_HEADER_CUSTOMER_SUCCESS';
export const SEARCH_HEADER_CUSTOMER_ERROR = 'SEARCH_HEADER_CUSTOMER_ERROR';
export const SEARCH_HEADER_CUSTOMER_RESET = 'SEARCH_HEADER_CUSTOMER_RESET';
// intrest List

export const INTEREST_LIST_REQUEST = 'INTEREST_LIST_REQUEST';
export const INTEREST_LIST_SUCCESS = 'INTEREST_LIST_SUCCESS';
export const INTEREST_LIST_ERROR = 'INTEREST_LIST_ERROR';


// login ActionTypes

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET';

// token expire
export const LOGIN_TOKEN_EXPIRE = 'LOGIN_TOKEN_EXPIRE';
export const LOGIN_TOKEN_RESET = 'LOGIN_TOKEN_RESET';


